---USE THE DB
use Autism;

---CHECK TABLE
SELECT * FROM AUTISM

---NUMBER OF CASES OVER THE YEARS OF PUBLISHED
SELECT COUNTRY,YEAR_PUBLISHED,SUM(NUMBER_OF_CASES) TOTAL_NUMBER_OF_CASES_PER_YEAR
FROM Autism
GROUP BY COUNTRY,YEAR_PUBLISHED 
ORDER BY COUNTRY,YEAR_PUBLISHED DESC; 

---NUMBER OF CASES OVER PER COUNTRY
SELECT COUNTRY,SUM(NUMBER_OF_CASES) TOTAL_NUMBER_OF_CASES_PER_COUNTRY
FROM Autism
GROUP BY COUNTRY
ORDER BY TOTAL_NUMBER_OF_CASES_PER_COUNTRY DESC; 

---AGE RANGE AND THEIR COUNT VS NUMBER OF CASES
SELECT A.COUNTRY,A.Study_Years, A.AGE_RANGE,COUNT(A.AGE_RANGE) AS AGE_RANGE_AFFECTED_VS_COUNT ,SUM(NUMBER_OF_CASES) AS TOTAL_NUMBER_OF_CASES
FROM Autism A
GROUP BY A.COUNTRY,A.AGE_RANGE,A.Study_Years
ORDER BY A.COUNTRY ,AGE_RANGE_AFFECTED_VS_COUNT  DESC

--COUNT OF IQ_SCORE_70 AND THE IQ SCORE

SELECT COUNTRY,A.IQ_SCORE_70,COUNT(IQ_SCORE_70) AS COUNT_OF_IQ_SCORE_70
FROM Autism A
GROUP BY A.IQ_SCORE_70,COUNTRY
ORDER BY COUNT_OF_IQ_SCORE_70 DESC,COUNTRY 

--COUNT AND AVERAGE COUNT PER COUNTRY
SELECT COUNTRY,AVG(IQ_SCORE_70) AS AVERAGE_IQ_PER_COUNTRY,
			   COUNT(IQ_SCORE_70) AS COUNT_OF_IQ_70	
			   --AVG(Non_Verbal_or_Minimally_Verbal) AS AVERAGE_VERBAL_MINIMALLY,
			   --COUNT(Non_Verbal_or_Minimally_Verbal) AS COUNT_VERBAL_MINIMALLY
			   
FROM Autism 
WHERE IQ_SCORE_70 IS NOT NULL 
GROUP BY COUNTRY
ORDER BY COUNT_OF_IQ_70 DESC,AVERAGE_IQ_PER_COUNTRY DESC,COUNTRY

--MOSTLY USED CASE INDETIFICATION METHODS 
SELECT CASE_IDENTIFICATION_METHOD,Study_Years,COUNTRY,COUNT(CASE_IDENTIFICATION_METHOD) AS NUMBER_OF_IDENTIFICATION_METHOD_USED 
FROM Autism 
GROUP BY CASE_IDENTIFICATION_METHOD,COUNTRY,Study_Years
ORDER BY NUMBER_OF_IDENTIFICATION_METHOD_USED DESC,COUNTRY

--AUTISM TYPES,COUNT VS COUNTRY

SELECT Autism_Types_Included ,COUNTRY
FROM Autism 
GROUP BY Autism_Types_Included,COUNTRY
ORDER BY COUNTRY

--CASE_CRTIERION 

SELECT COUNTRY,CASE_CRITERION,COUNT(*) CRITERIA_VS_CRITERIA_COUNT_PER_COUNTRY
FROM Autism
GROUP BY CASE_CRITERION,COUNTRY
ORDER BY COUNTRY,CRITERIA_VS_CRITERIA_COUNT_PER_COUNTRY DESC



--number of Countries that performed studies

WITH TEST  AS (
SELECT COUNTRY,COUNT(COUNTRY) COUNT_OF_STUDIES	
FROM Autism 
GROUP BY COUNTRY
 ) 
SELECT T.* ,
  	DENSE_RANK() OVER (ORDER BY COUNT_OF_STUDIES DESC) STUDY_COUNT_RANK
FROM TEST T




SELECT country,Autism_Types_Included
FROM AUTISM

SELECT COUNTRY,SAMPLE_SIZE,NUMBER_OF_CASES
FROM AUTISM 
GROUP 
--GET THE MALE TO FEMALE RATION OF CASES
SELECT COUNTRY,MALE_FEMALE_SEX_RATIO
FROM AUTISM 
WHERE MALE_FEMALE_SEX_RATIO IS NOT NULL
	
SELECT COUNTRY,CASE_CRITERION,COUNT(CASE_CRITERION) AS COUNT_OF_cRITERION
FROM Autism
GROUP BY CASE_CRITERION,COUNTRY

SELECT COUNTRY,Percentage_of_Individual_Co_occurring_Conditions 
FROM autism
WHERE Percentage_of_Individual_Co_occurring_Conditions IS NOT NULL

USE Autism
SELECT country,White_Black_Prevalence_Ratio,Non_Hispanic_White_Hispanic_Prevalence_Ratio
FROM Autism
where White_Black_Prevalence_Ratio is not null and Non_Hispanic_White_Hispanic_Prevalence_Ratio is not null

--STUDY B/N YEARS
SELECT MIN(STUDY_YEARS) AS FRIST_STUDY_YEAR,MAX(STUDY_YEARS) AS LAST_STUDY_YEARS
FROM Autism

